### ISSUE TITLE
How can I use typecs to compile my .ts sources

### ISSUE THREAD

**Issue by Leprosy** [axmor/typecs#90]
Sorry...it seems I can't found this in the documentation of the project. I have a javascript project, added TypeScript support, but the compiling isn't happening. :(

**Comment by p-kudrin** [comment]
Make sure the Node.js plugins is installed and enabled.
TypEcs support any kind of project. To enable TypeScript support you need add TypeScript nature for project from context menu: 
![addsupport](https://cloud.githubusercontent.com/assets/10921202/10931631/e33fd6fc-82ea-11e5-88c0-d1d8bf979edb.png)

Now you need to configure TypeScript compiler settings in the project properties:
![compilation](https://cloud.githubusercontent.com/assets/10921202/10931661/1a89a408-82eb-11e5-8980-2998f078e97e.png)

If you set target as a single .js file all *.ts files will be compiled into one output file. Otherwise each .ts file will be compiled in a separate .js file. Now your TypeScript code can be compiled.

**Comment by Leprosy** [comment]
Great!! thanks ;)
